### ISSUE TITLE
is it possible to seed the RNG?

### ISSUE THREAD

**Issue by seiyria** [PatGleeson101/MathicallJS#1]
I didn't see anything along these lines in the docs, but I noticed there were some references to seed in the code itself. I also didn't see in the docs how you would get a random number, despite being mentioned in the readme. Is it possible to use this library to get a random number with a specific seed?

**Comment by PatGleeson101** [comment]
Yes, it is. Apologies about the docs, I'm still updating them.

To get seeded random numbers, you can initialise a generator, where the last argument is its seed. The first two or so arguments describe the distribution (e.g. the range for uniform random numbers, or the mean and standard deviation for normally distributed numbers). For example:

```javascript
var rand = Mathicall.random.Norm(0, 1, 104563);
rand() //Random normally distributed number between 0 and 1
rand() //Another 
```

You can check the seed as follows:
```javascript
rand.seed() //The current seed
```

Or reset the seed by providing a new one:
```javascript
rand.seed(3054) //The generator is reset with seed 3054
```

**Comment by seiyria** [comment]
Thanks, this is great stuff! I'll look forward to the docs then.
